### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by joeymays** [joeymays/Red4Craft-WC-RPack#1]
To Fix:

- [ ] Minecart icons
- [ ] Flower pot icon
- [ ] Smoke/cobwebs
- [ ] Rotate Light Gray Stained Clay a quarter turn and replace Brown Stained Clay with it.

**Comment by steve7992** [comment]
Rotate Light Gray Stained Clay a quarter turn and replace Brown Stained Clay with it.
